local function example_2_listener(self, message_id, message)
	if type(message) == "string" then
		print("example2", message_id, message, "(" .. string.len(message) .. " bytes)")
	else
		pprint("example2", message_id, message)
	end
end

function init(self)
	if jstodef then
		jstodef.add_listener(example_2_listener)
	end
end

function final(self)
	if jstodef then
		jstodef.remove_listener(example_2_listener)
	end
end