local function example_1_listener(self, message_id, message)
	if type(message) == "string" then
		print("example1", message_id, message, "(" .. string.len(message) .. " bytes)")
	else
		pprint("example1", message_id, message)
	end
end

function init(self)
	if jstodef then
		jstodef.add_listener(example_1_listener)
	end
end

function final(self)
	if jstodef then
		jstodef.remove_listener(example_1_listener)
	end
end
